### ISSUE TITLE
Set volumes to read-only

### ISSUE THREAD

**Issue by d4rklynk** [tommytran732/Signal-TLS-Proxy#5]
If the files are not used after they have been mounted in the container. We can set them to ro.

- [Line 8 to 9](https://github.com/ArcticFoxes-net/Signal-TLS-Proxy/blob/main/docker-compose.yml#L8)
- [Line 28](https://github.com/ArcticFoxes-net/Signal-TLS-Proxy/blob/main/docker-compose.yml#L28)
- [Line 41 to 42](https://github.com/ArcticFoxes-net/Signal-TLS-Proxy/blob/main/docker-compose.yml#L41)

**Comment by TommyTran732** [comment]
> [Line 41 to 42](https://github.com/ArcticFoxes-net/Signal-TLS-Proxy/blob/main/docker-compose.yml#L41)

I don't think this can be RO because certbot needs to write stuff to `/etc/letsencrypt`. The others seem fine.

**Comment by d4rklynk** [comment]
I'll make a PR

**Comment by d4rklynk** [comment]
PR -> https://github.com/ArcticFoxes-net/Signal-TLS-Proxy/pull/6

**Comment by TommyTran732** [comment]
Merged
